@url=http://localhost:8080

###
POST {{url}}/events
content-type: application/json

{
    "name": "sample",
    "timestamp": "{{$datetime iso8601}}"
}

###
POST {{url}}/events/count-per-time-report
content-type: application/json

{
    "name": "sample",
    "timeUnit": ["MINUTE"],
    "start": "{{$datetime iso8601 -10 m}}",
    "end": "{{$datetime iso8601}}"
}